name: CI workflow for calci app

on: 
  push:
    branches:
     - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
         py -m pip install --upgrade pip
         pip install -r requirements.txt

      - name: Run unit tests
        run: |
         $env:PYTHONPATH = "$env:PYTHONPATH;."
         py -m unittests discover tests
        shell: powershell
      
      - name: Send notifications on failure
        if: failure()
        run : echo "Build failure"

